Dataset Understanding

In [2]:
import pandas as pd
df=pd.read_csv("TV_channel_dataset.csv")
print(df)

       Channel_ID  Channel_Name Language Channel_Category   Popular_Show  \
0          100000        Sun TV    Tamil    Entertainment          Kayal
1          100001      Vijay TV    Tamil    Entertainment   Super Singer
2          100002  Kalaignar TV    Tamil    Entertainment        Serials
3          100003     Zee Tamil    Tamil    Entertainment   Comedy Shows
4          100004   Star Sports  English           Sports        Cricket
...           ...           ...      ...              ...            ...
60244      160244           KTV    Tamil           Movies  Comedy Movies
60245      160245      Vijay TV    Tamil    Entertainment   Super Singer
60246      160246           KTV    Tamil           Movies   Tamil Movies
60247      160247      Vijay TV    Tamil    Entertainment      Bigg Boss
60248      160248   Sony Sports  English           Sports       Football

      Show_Category  No_of_Shows Avg_Viewers  Avg_Rating Total_Likes  \
0            Serial           18     1328200         4.8      139254
1             Music           37     7531415         3.4      418114
2            Serial           34     1588719         3.0      154340
3            Comedy            8     6624711         3.7      154409
4            Sports           25     1834834         3.6      236690
...             ...          ...         ...         ...         ...
60244        Movies           16     6868163         4.4      363058
60245         Music           37     9755903         3.6      264195
60246        Movies           30     9644523         4.0     1267227
60247       Reality            8    10455540         4.8      622637
60248        Sports           40     7006275         3.8      178914

      Social_Media_Followers YouTube_Views HD_Available  Years_Active  \
0                     879699      80947519          Yes            31
1                    6586832      72892761          Yes            20
2                    6794133      46798080           No            12
3                     598277      34681210          Yes            18
4                    5473089      65168770          Yes            17
...                      ...           ...          ...           ...
60244                2304619      93768233          Yes             8
60245              3,320,652      30340824           No            12
60246                 949984      62809727          Yes            33
60247                7973100      87007314          Yes            33
60248                6421598      31419702           No             6

       Subscription_Fee Monthly_Reach
0                 180.0       2866591
1                 300.0      16857090
2                 202.0       2081425
3                 125.0      14372542
4                  93.0           NaN
...                 ...           ...
60244             327.0      18160451
60245             273.0      25700655
60246             462.0      17880020
60247              85.0      21394990
60248             270.0      15016263

[60249 rows x 16 columns]

In [3]:
print(df.head(10))

   Channel_ID  Channel_Name Language Channel_Category           Popular_Show  \
0      100000        Sun TV    Tamil    Entertainment                  Kayal
1      100001      Vijay TV    Tamil    Entertainment           Super Singer
2      100002  Kalaignar TV    Tamil    Entertainment                Serials
3      100003     Zee Tamil    Tamil    Entertainment           Comedy Shows
4      100004   Star Sports  English           Sports                Cricket
5      100005      Vijay TV    Tamil    Entertainment  Kalakka Povathu Yaaru
6      100006        Sun TV    Tamil    Entertainment           Comedy Shows
7      100007        Raj TV    Tamil    Entertainment       Special Programs
8      100008  Kalaignar TV    Tamil    Entertainment            Movie Shows
9      100009   Star Sports  English           Sports                Cricket

  Show_Category  No_of_Shows Avg_Viewers  Avg_Rating Total_Likes  \
0        Serial           18     1328200         4.8      139254
1         Music           37     7531415         3.4      418114
2        Serial           34     1588719         3.0      154340
3        Comedy            8     6624711         3.7      154409
4        Sports           25     1834834         3.6      236690
5       Reality            8     5037507         NaN      131232
6        Comedy           22    11608941         4.2     1339230
7       Reality            5     7410930         3.7      564570
8        Movies           26     8405345         4.5      914684
9        Sports           31     9656344         3.9     1310226

  Social_Media_Followers YouTube_Views HD_Available  Years_Active  \
0                 879699      80947519          Yes            31
1                6586832      72892761          Yes            20
2                6794133      46798080           No            12
3                 598277      34681210          Yes            18
4                5473089      65168770          Yes            17
5                6242263      63225061           No            26
6                2545397      52731619          Yes            17
7                7999756      48553151          Yes            28
8                6391772      10028469           No            13
9                5129744      42114973          Yes            11

   Subscription_Fee Monthly_Reach
0             180.0       2866591
1             300.0      16857090
2             202.0       2081425
3             125.0      14372542
4              93.0           NaN
5             482.0      17047827
6             145.0      32467309
7             221.0      26323712
8             443.0      16434208
9             203.0      41070047

In [4]:
print(df.tail(10))

       Channel_ID Channel_Name Language Channel_Category   Popular_Show  \
60239      160239     Vijay TV    Tamil    Entertainment        Serials
60240      160240       Raj TV    Tamil    Entertainment    Movie Shows
60241      160241       Sun TV    Tamil    Entertainment  Vanathai Pola
60242      160242      Jaya TV    Tamil    Entertainment    Music Shows
60243      160243  Sony Sports  English           Sports       Football
60244      160244          KTV    Tamil           Movies  Comedy Movies
60245      160245     Vijay TV    Tamil    Entertainment   Super Singer
60246      160246          KTV    Tamil           Movies   Tamil Movies
60247      160247     Vijay TV    Tamil    Entertainment      Bigg Boss
60248      160248  Sony Sports  English           Sports       Football

      Show_Category  No_of_Shows Avg_Viewers  Avg_Rating Total_Likes  \
60239        Serial           24     5436217         3.9      222127
60240        Movies           37     1652693         4.5       97895
60241        Serial           18     2280005         4.5      176651
60242         Music           31     3416023         2.9      443920
60243        Sports           36    10004928         2.9     1234370
60244        Movies           16     6868163         4.4      363058
60245         Music           37     9755903         3.6      264195
60246        Movies           30     9644523         4.0     1267227
60247       Reality            8    10455540         4.8      622637
60248        Sports           40     7006275         3.8      178914

      Social_Media_Followers YouTube_Views HD_Available  Years_Active  \
60239                6252029      20204170          Yes            33
60240                3582801      52903242          Yes             4
60241                2503084      12862964          Yes            31
60242                 159552      72475828          Yes            15
60243                4184000       3568883          Yes            12
60244                2304619      93768233          Yes             8
60245              3,320,652      30340824           No            12
60246                 949984      62809727          Yes            33
60247                7973100      87007314          Yes            33
60248                6421598      31419702           No             6

       Subscription_Fee Monthly_Reach
60239             392.0      15684228
60240              80.0       4595930
60241             161.0       3494497
60242             476.0       7636666
60243             435.0      20490846
60244             327.0      18160451
60245             273.0      25700655
60246             462.0      17880020
60247              85.0      21394990
60248             270.0      15016263

In [5]:
print(df.shape)

(60249, 16)

In [6]:
print(df.columns)

Index(['Channel_ID', 'Channel_Name', 'Language', 'Channel_Category',
       'Popular_Show', 'Show_Category', 'No_of_Shows', 'Avg_Viewers',
       'Avg_Rating', 'Total_Likes', 'Social_Media_Followers', 'YouTube_Views',
       'HD_Available', 'Years_Active', 'Subscription_Fee', 'Monthly_Reach'],
      dtype='str')

In [7]:
print(df.dtypes)

Channel_ID                  int64
Channel_Name                  str
Language                      str
Channel_Category              str
Popular_Show                  str
Show_Category                 str
No_of_Shows                 int64
Avg_Viewers                   str
Avg_Rating                float64
Total_Likes                   str
Social_Media_Followers        str
YouTube_Views                 str
HD_Available                  str
Years_Active                int64
Subscription_Fee          float64
Monthly_Reach                 str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60249 entries, 0 to 60248
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Channel_ID              60249 non-null  int64
 1   Channel_Name            59898 non-null  str
 2   Language                59998 non-null  str
 3   Channel_Category        60249 non-null  str
 4   Popular_Show            59813 non-null  str
 5   Show_Category           60249 non-null  str
 6   No_of_Shows             60249 non-null  int64
 7   Avg_Viewers             59837 non-null  str
 8   Avg_Rating              59952 non-null  float64
 9   Total_Likes             59953 non-null  str
 10  Social_Media_Followers  60016 non-null  str
 11  YouTube_Views           59955 non-null  str
 12  HD_Available            60249 non-null  str
 13  Years_Active            60249 non-null  int64
 14  Subscription_Fee        59976 non-null  float64
 15  Monthly_Reach           59904 non-null  str
dtypes: float64(2), int64(3), str(11)
memory usage: 12.0 MB

In [9]:
df.describe()

,Channel_ID,No_of_Shows,Avg_Rating,Years_Active,Subscription_Fee
count,60249.000000,60249.000000,59952.000000,60249.000000,59976.000000
mean,130124.000000,22.517104,3.649840,18.992083,274.525077
std,17392.532521,10.384328,0.732191,9.572759,130.654765
min,100000.000000,5.000000,-1.000000,0.000000,-100.000000
25%,115062.000000,14.000000,3.000000,11.000000,161.000000
50%,130124.000000,23.000000,3.600000,19.000000,274.000000
75%,145186.000000,32.000000,4.300000,27.000000,388.000000
max,160248.000000,40.000000,6.500000,75.000000,500.000000

In [10]:
# Numerical columns
print(df.select_dtypes(include='number').columns)

# Categorical columns
print(df.select_dtypes(include='object').columns)

Index(['Channel_ID', 'No_of_Shows', 'Avg_Rating', 'Years_Active',
       'Subscription_Fee'],
      dtype='str')
Index(['Channel_Name', 'Language', 'Channel_Category', 'Popular_Show',
       'Show_Category', 'Avg_Viewers', 'Total_Likes', 'Social_Media_Followers',
       'YouTube_Views', 'HD_Available', 'Monthly_Reach'],
      dtype='str')

C:\Users\selsh\AppData\Local\Temp\ipykernel_13460\319515891.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include='object').columns)

In [11]:
df["Channel_Name"].nunique()            #Find the number of unique TV channels.

24

In [12]:
df["Channel_Name"].unique()                      #Display all unique channel names.

<ArrowStringArray>
[      'Sun TV',     'Vijay TV', 'Kalaignar TV',    'Zee Tamil',
  'Star Sports',       'Raj TV',          'KTV',  'Sony Sports',
 'Colors Tamil',      'Jaya TV',     'ZeeTamil',        'SunTV',
            nan, 'colors tamil', 'COLORS TAMIL',  'ColorsTamil',
     'vijay tv',       'sun tv',    'zee tamil',    'Vijay  TV',
      'unknown',       'SUN TV',      'VijayTV',    'ZEE TAMIL',
     'VIJAY TV']
Length: 25, dtype: str

In [13]:
df["Show_Category"].nunique()

7

Data Quality Checking

In [14]:
print(df.isnull().values.any())             #	Check whether the dataset contains missing values.

True

In [15]:
df.isnull().sum()              # Find the number of missing values in each column.

Channel_ID                  0
Channel_Name              351
Language                  251
Channel_Category            0
Popular_Show              436
Show_Category               0
No_of_Shows                 0
Avg_Viewers               412
Avg_Rating                297
Total_Likes               296
Social_Media_Followers    233
YouTube_Views             294
HD_Available                0
Years_Active                0
Subscription_Fee          273
Monthly_Reach             345
dtype: int64

In [16]:
print(df.isnull().mean() * 100)          #Calculate the percentage of missing values in each column.

Channel_ID                0.000000
Channel_Name              0.582582
Language                  0.416604
Channel_Category          0.000000
Popular_Show              0.723663
Show_Category             0.000000
No_of_Shows               0.000000
Avg_Viewers               0.683829
Avg_Rating                0.492954
Total_Likes               0.491294
Social_Media_Followers    0.386728
YouTube_Views             0.487975
HD_Available              0.000000
Years_Active              0.000000
Subscription_Fee          0.453120
Monthly_Reach             0.572624
dtype: float64

In [17]:
print(df.duplicated().values.any())  #15.	Calculate the percentage of missing values in each column

False

In [18]:
df.duplicated().value_counts()

False    60249
Name: count, dtype: int64

In [19]:
print(df['Channel_Name'].str.lower().value_counts())          #	Check for inconsistent channel names.

Channel_Name
kalaignar tv    6158
star sports     6035
jaya tv         6004
sony sports     5989
ktv             5978
sun tv          5942
vijay tv        5894
colors tamil    5864
zee tamil       5854
raj tv          5829
suntv             81
zeetamil          80
colorstamil       67
vijay  tv         44
vijaytv           44
unknown           35
Name: count, dtype: int64

In [20]:
#print(df['Channel_Name'].unique())
df['Channel_Name'] = df['Channel_Name'].replace({
    'SunTV': 'Sun TV',
    'sun tv': 'Sun TV',
    'SUN TV': 'Sun TV',

    'VijayTV': 'Vijay TV',
    'vijay tv': 'Vijay TV',
    'VIJAY TV': 'Vijay TV',
    'Vijay  TV': 'Vijay TV',

    'ZeeTamil': 'Zee Tamil',
    'zee tamil': 'Zee Tamil',
    'ZEE TAMIL': 'Zee Tamil',

    'colors tamil': 'Colors Tamil',
    'COLORS TAMIL': 'Colors Tamil',
    'ColorsTamil': 'Colors Tamil'
})

In [21]:
print(df['Channel_Name'].unique())   #to check the inconsistent values

<ArrowStringArray>
[      'Sun TV',     'Vijay TV', 'Kalaignar TV',    'Zee Tamil',
  'Star Sports',       'Raj TV',          'KTV',  'Sony Sports',
 'Colors Tamil',      'Jaya TV',            nan,      'unknown']
Length: 12, dtype: str

In [22]:
print(df[(df['Avg_Rating'] < 0) | (df['Avg_Rating'] > 5)])

       Channel_ID  Channel_Name Language Channel_Category  \
1592       101592     Zee Tamil    Tamil    Entertainment
1697       101697       Jaya TV    Tamil    Entertainment
2660       102660        Sun TV    Tamil    Entertainment
2812       102812  Colors Tamil    Tamil    Entertainment
3373       103373  Kalaignar TV    Tamil    Entertainment
4210       104210        Raj TV    Tamil    Entertainment
4635       104635   Sony Sports  English           Sports
7220       107220       Jaya TV    Tamil    Entertainment
12179      112179      Vijay TV    Tamil    Entertainment
12726      112726   Star Sports  English           Sports
13778      113778     Zee Tamil    Tamil    Entertainment
13793      113793  Kalaignar TV    Tamil    Entertainment
14045      114045  Kalaignar TV    Tamil    Entertainment
14218      114218  Colors Tamil    Tamil    Entertainment
19210      119210   Star Sports  English           Sports
20945      120945        Sun TV    Tamil    Entertainment
21841      121841       Jaya TV    Tamil    Entertainment
21992      121992       Jaya TV    Tamil    Entertainment
23450      123450        Sun TV    Tamil    Entertainment
26181      126181   Star Sports  English           Sports
26376      126376  Colors Tamil    Tamil    Entertainment
26823      126823  Kalaignar TV    Tamil    Entertainment
27145      127145      Vijay TV    Tamil    Entertainment
32617      132617           NaN    Tamil    Entertainment
33074      133074  Kalaignar TV    Tamil    Entertainment
33371      133371       Jaya TV    Tamil    Entertainment
34885      134885  Colors Tamil    Tamil    Entertainment
35189      135189      Vijay TV    Tamil    Entertainment
36673      136673   Sony Sports  English           Sports
40998      140998   Star Sports  English           Sports
41373      141373     Zee Tamil    Tamil    Entertainment
41596      141596   Sony Sports  English           Sports
42996      142996      Vijay TV    Tamil    Entertainment
43123      143123           KTV    Tamil           Movies
44298      144298        Raj TV    Tamil    Entertainment
45029      145029      Vijay TV    Tamil    Entertainment
45110      145110        Sun TV    Tamil    Entertainment
45559      145559       Jaya TV    Tamil    Entertainment
45691      145691  Kalaignar TV    Tamil    Entertainment
47447      147447  Colors Tamil    Tamil    Entertainment
47791      147791   Sony Sports  English           Sports
48315      148315        Sun TV    Tamil    Entertainment
50165      150165  Colors Tamil    Tamil    Entertainment
51488      151488        Raj TV    Tamil    Entertainment
53649      153649        Raj TV    Tamil    Entertainment
54766      154766  Kalaignar TV    Tamil    Entertainment
57073      157073           KTV    Tamil           Movies
59916      159916      Vijay TV    Tamil    Entertainment

                Popular_Show Show_Category  No_of_Shows Avg_Viewers  \
1592            Comedy Shows        Comedy           29     6882038
1697        Special Programs       Reality           37     2833611
2660            Comedy Shows        Comedy           32    10964174
2812           Reality Shows       Reality           12     2113827
3373        Special Programs       Reality           12     2324610
4210        Special Programs       Reality           15     9844263
4635               Badminton        Sports           31     8929648
7220             Movie Shows        Movies           12     5637268
12179           Super Singer         Music           32     1332239
12726                Cricket        Sports            5     4707858
13778                Serials        Serial           26     8534110
13793            Music Shows         Music           36     1458238
14045       Special Programs       Reality           33     6391983
14218                Serials        Serial           37    10611940
19210                Cricket        Sports           40     3355671
20945          Reality Shows       Reality            6     1914871
21841                Serials        Serial           24    10114725
21992       Special Programs       Reality           11     4469097
23450           Comedy Shows        Comedy           33     6680767
26181                 Hockey        Sports           20     1130534
26376               Abhirami        Serial           10     2662708
26823            Music Shows         Music           39     2091937
27145  Kalakka Povathu Yaaru       Reality           30    10990420
32617                Serials        Serial           20     7757377
33074           Comedy Shows        Comedy           35     2049780
33371       Special Programs       Reality           20         NaN
34885           Comedy Shows        Comedy           36     6890731
35189      Cooku with Comali       Cooking           30     9317305
36673              Badminton        Sports           40     5588311
40998               Football        Sports           13     4731354
41373          Reality Shows       Reality            9     4923386
41596              Badminton        Sports           14     5474529
42996                Serials        Serial           21     9878803
43123           Tamil Movies        Movies           14     3625961
44298            Music Shows         Music           27     7362619
45029           Super Singer         Music           32     5992063
45110           Comedy Shows        Comedy            5     5351672
45559            Music Shows         Music           31         NaN
45691                Serials        Serial           23     1350844
47447               Abhirami        Serial           20     1736278
47791              Wrestling        Sports           28     2209913
48315           Comedy Shows        Comedy           40     1413582
50165                Serials        Serial           14     8223293
51488            Movie Shows        Movies           33     9688477
53649            Movie Shows        Movies           34      566456
54766                Serials        Serial           18     8691462
57073          Comedy Movies        Movies           39     7772026
59916                Serials        Serial           13     4958505

       Avg_Rating Total_Likes Social_Media_Followers YouTube_Views  \
1592          5.5      224019                2363687      51279669
1697         -1.0      331721                2122607      57912459
2660         -1.0     1061476                2244107       9999545
2812         -1.0      175120                5175605      59240554
3373         -1.0         NaN                 173045      41255163
4210          6.5      866938                7166648      54504581
4635          6.5      876909                4202024       3458204
7220         -1.0      358209                2535326       6692772
12179        -1.0      134443                2651253      96507710
12726         5.5      175454                 457610      27174075
13778         6.5     1005147                1082257      86023625
13793         5.5       47224                6429310      68096597
14045        -1.0      306872                3502239       2527398
14218         5.5      717612                    NaN      41448501
19210         6.5      333999                1393819      47845899
20945         6.5      247851                5888388       9488785
21841         6.5      304006                4040902      47247384
21992         5.5      268337                 756547      43121593
23450        -1.0      875153                 519449      23842454
26181         6.5       97628                6812452      94281384
26376        -1.0      154678                1296708      15825222
26823        -1.0      106870                4164210      18288211
27145        -1.0      287787                6491574      33472233
32617         5.5      750883                5541612      80228029
33074         6.5      257568                7039476      58941774
33371         6.5      222145                6733198      56526060
34885         5.5      852053                1808721           NaN
35189         6.5      332330                1850856      97875335
36673         5.5      578356                4018290       1345593
40998         6.5      342889                3063043      58302556
41373        -1.0      372306                6645363      64176569
41596         5.5      659146                3712566      45073085
42996         6.5      721323                7119377      14621946
43123         5.5      244442                3524311       3960406
44298         6.5     1022486                5203058      48633770
45029        -1.0      277158                4452114      79880520
45110         5.5      547358                2851385      83067326
45559        -1.0       71601                3932362      44739734
45691        -1.0      145099                6621932           NaN
47447         6.5       41975                7758235      16272475
47791         5.5      284148                3321607      84376489
48315         6.5      155292                6495919      27246407
50165         5.5      696469                7992009      67527605
51488        -1.0     1213678                3716521      73907289
53649         5.5       51071                4957082      94841914
54766         6.5      403068                3470468      88084088
57073         6.5      844142                3207617      89668370
59916         5.5      283348                4609973      85055898

      HD_Available  Years_Active  Subscription_Fee Monthly_Reach
1592           Yes            22             349.0      26546776
1697           Yes             8             222.0       6474134
2660           Yes            32             182.0      47934902
2812           Yes             3             272.0       6812549
3373           Yes             7              64.0       8650408
4210           Yes            27             328.0      26684189
4635           Yes             4             230.0      17451145
7220           Yes            20             131.0      21923193
12179          Yes            12             362.0       2230446
12726          Yes            13             365.0      11615162
13778          Yes            19             427.0      34620204
13793           No            25             452.0       3212532
14045          Yes            27             133.0      24263845
14218          Yes            32             473.0      24183327
19210          Yes            27             307.0       7191458
20945          Yes            29             460.0       2649373
21841          Yes            30             285.0      34827324
21992          Yes            21             207.0       5908479
23450          Yes             6             435.0      21391558
26181          Yes            26             194.0       1676637
26376          Yes            23              57.0       6798516
26823          Yes             3             226.0       7943192
27145          Yes            14             363.0      13778812
32617          Yes             5             437.0      29444813
33074          Yes            15             184.0       7494981
33371          Yes            32             303.0       9033443
34885          Yes            13             384.0      27661792
35189          Yes             5             229.0      18344265
36673          Yes             7             485.0      16640517
40998          Yes            25              89.0      11724826
41373          Yes            15             375.0      12666869
41596          Yes            15              95.0      23827350
42996          Yes            14             125.0      26579432
43123           No             8             499.0      13050010
44298          Yes            28             458.0      25900246
45029          Yes            10             486.0      21197623
45110          Yes             8             342.0      22365464
45559          Yes            34             454.0       3877851
45691           No            24             165.0       4378582
47447          Yes            20             102.0       5624637
47791          Yes            23             356.0       9576744
48315          Yes            23              71.0       2586919
50165          Yes             8             399.0      15303374
51488          Yes            17             486.0      14599954
53649          Yes            17             225.0       1288757
54766          Yes             4              50.0      16507305
57073          Yes            11             287.0      26142949
59916          Yes            14             142.0      15615379

# whether Avg_Viewers contains invalid values

Meaning:
Avg_Viewers represents the average number of viewers. A negative number of viewers is invalid

In [23]:
print(df[df['Years_Active'] < 0])   #Check whether Avg_Viewers contains invalid values
print(df['Years_Active'].describe())

Empty DataFrame
Columns: [Channel_ID, Channel_Name, Language, Channel_Category, Popular_Show, Show_Category, No_of_Shows, Avg_Viewers, Avg_Rating, Total_Likes, Social_Media_Followers, YouTube_Views, HD_Available, Years_Active, Subscription_Fee, Monthly_Reach]
Index: []
count    60249.000000
mean        18.992083
std          9.572759
min          0.000000
25%         11.000000
50%         19.000000
75%         27.000000
max         75.000000
Name: Years_Active, dtype: float64

	Check whether HD_Available contains only Yes and No.

In [24]:
set(df['HD_Available'].dropna().unique()).issubset({'Yes', 'No'})

True

24.	Identify NA, N/A, unknown, and blank values

In [25]:
# Check for NA, N/A, unknown, and blank values
df[df.astype(str).apply(
    lambda x: x.str.strip().str.lower().isin(['na', 'n/a', 'unknown', ''])
).any(axis=1)]

,Channel_ID,Channel_Name,Language,Channel_Category,Popular_Show,Show_Category,No_of_Shows,Avg_Viewers,Avg_Rating,Total_Likes,Social_Media_Followers,YouTube_Views,HD_Available,Years_Active,Subscription_Fee,Monthly_Reach
1924,101924,Vijay TV,Tamil,Entertainment,unknown,Reality,6,11154579,3.6,998030,5923224,20842520,No,35,393.0,16267966
2337,102337,unknown,English,Sports,Football,Sports,18,7460992,3.2,612416,1498006,24481092,Yes,30,224.0,27722785
2405,102405,Jaya TV,Tamil,Entertainment,unknown,Reality,19,4478378,3.8,153522,5470722,20573881,Yes,13,311.0,15098769
2534,102534,Sun TV,unknown,Entertainment,Singapenne,Serial,25,10262802,2.7,1372433,338396,89968510,Yes,15,307.0,35014250
3364,103364,unknown,Tamil,Entertainment,Comedy Shows,Comedy,31,482781,2.5,66392,6385731,56517334,Yes,35,126.0,1674500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56006,156006,unknown,English,Sports,Tennis,Sports,5,8092110,2.9,344847,837215,5798417,Yes,7,81.0,31337435
56564,156564,Zee Tamil,Tamil,Entertainment,unknown,Music,40,5447769,3.8,612499,688118,87831057,Yes,31,414.0,15101645
58593,158593,unknown,Tamil,Entertainment,Special Programs,Reality,31,7519525,4.8,1021580,5403319,21199117,Yes,4,347.0,13301644
58762,158762,unknown,Tamil,Entertainment,Comedy Shows,Comedy,30,5544299,4.2,632856,4999243,48876905,Yes,3,383.0,15399011
59140,159140,Vijay TV,Tamil,Entertainment,unknown,Reality,19,8053663,4.8,269088,2695162,19949397,Yes,7,106.0,13173769

25.	Identify columns where numeric values are stored as text.

In [26]:
for col in df.columns:
    converted = pd.to_numeric(df[col], errors='coerce')
    invalid = converted.notna() & df[col].notna() & converted.isna()
    
    if invalid.any():
        print(col)
        print(df.loc[invalid, col].unique())

In [27]:
df['Total_Likes'].apply(type).value_counts()

Total_Likes
<class 'str'>      59953
<class 'float'>      296
Name: count, dtype: int64

Data Cleaning

26.	Standardize the Channel_Name values.

In [28]:
# Remove extra spaces
df['Channel_Name'] = df['Channel_Name'].str.strip()

# Standardize channel names
df['Channel_Name'] = df['Channel_Name'].replace({
    'SunTV': 'Sun TV',
    'ZeeTamil': 'Zee Tamil',
    'colors tamil': 'Colors Tamil',
    'COLORS TAMIL': 'Colors Tamil',
    'ColorsTamil': 'Colors Tamil',
    'vijay tv': 'Vijay TV'
})

# Check the standardized values
print(df['Channel_Name'].unique())

<ArrowStringArray>
[      'Sun TV',     'Vijay TV', 'Kalaignar TV',    'Zee Tamil',
  'Star Sports',       'Raj TV',          'KTV',  'Sony Sports',
 'Colors Tamil',      'Jaya TV',            nan,      'unknown']
Length: 12, dtype: str

27.	Handle missing values appropriately.

In [29]:
df.isnull().sum()

Channel_ID                  0
Channel_Name              351
Language                  251
Channel_Category            0
Popular_Show              436
Show_Category               0
No_of_Shows                 0
Avg_Viewers               412
Avg_Rating                297
Total_Likes               296
Social_Media_Followers    233
YouTube_Views             294
HD_Available                0
Years_Active                0
Subscription_Fee          273
Monthly_Reach             345
dtype: int64

In [30]:
numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())  #For numeric columns, use the median

In [31]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])  #For categorical columns, use the mode:

C:\Users\selsh\AppData\Local\Temp\ipykernel_13460\2128901788.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [32]:
print(df.isnull().sum())

Channel_ID                0
Channel_Name              0
Language                  0
Channel_Category          0
Popular_Show              0
Show_Category             0
No_of_Shows               0
Avg_Viewers               0
Avg_Rating                0
Total_Likes               0
Social_Media_Followers    0
YouTube_Views             0
HD_Available              0
Years_Active              0
Subscription_Fee          0
Monthly_Reach             0
dtype: int64

28.	Remove duplicate records.

In [33]:
# Check number of duplicate records
print("Duplicates:", df.duplicated().sum())

# Remove duplicate records
df = df.drop_duplicates()

# Check again
print("Duplicates after removal:", df.duplicated().sum())

Duplicates: 0
Duplicates after removal: 0

29.	Correct invalid Avg_Rating values.

In [36]:
import pandas as pd

# Example dataset
data = {
    "Channel_ID": [1, 2, 3, 4],
    "Channel_Name": ["A", "B", "C", "D"],
    "Avg_Rating": [4.5, -1, 6.2, None]  # invalid values included
}

df = pd.DataFrame(data)

# ✅ Step 1: Define valid range (0–5)
valid_min, valid_max = 0, 5

# ✅ Step 2: Identify invalid values
invalid = df[(df["Avg_Rating"] < valid_min) | (df["Avg_Rating"] > valid_max) | (df["Avg_Rating"].isna())]
print("Invalid Ratings:\n", invalid)

# ✅ Step 3: Correct invalid values
# Option 1: Replace with NaN
df.loc[(df["Avg_Rating"] < valid_min) | (df["Avg_Rating"] > valid_max), "Avg_Rating"] = None

# Option 2: Cap values within range
df["Avg_Rating"] = df["Avg_Rating"].clip(lower=valid_min, upper=valid_max)

print("\nCorrected DataFrame:\n", df)

Invalid Ratings:
    Channel_ID Channel_Name  Avg_Rating
1           2            B        -1.0
2           3            C         6.2
3           4            D         NaN

Corrected DataFrame:
    Channel_ID Channel_Name  Avg_Rating
0           1            A         4.5
1           2            B         NaN
2           3            C         NaN
3           4            D         NaN